const generatedBibEntries = {
    "10.2118/190527-MS": {
        "abstract": "\"{Despite the importance of learning from incidents, little is known about the indicators that signal whether people have actually learnt. Previous research has shown that learning is dependent on context; a software engineer and an operator at a petrochemical plant display learning in different ways, so the indicators of whether or not they have learnt will differ. Therefore it is important that energy organisations are able to recognise indicators of learning following an incident that are relevant to their context. The objective of this study is to explore ways of understanding whether individuals are learning from incidents, and provide a general model that companies can use as a starting point in evaluating learning.The Open University, in collaboration with the Energy Institute, undertook interviews with 18 workers at a European site of a multinational energy company. The participants came from a variety of positions in both operations and maintenance, ranging from front-end operators to managers. A model of professional learning was used to guide a thematic analysis of what participants viewed as effective learning from incidents.The interviews provided many examples of ways that individual practice and site processes had changed as a result of learning from incidents. Indicators of learning ranged from individual traits, such as accurate perception of risks, to changes in leadership priorities. While the number of incidents has been used in both research and practice as an indicator of learning, the interviews demonstrated that there are many ways in which learning can be evidenced. Understanding what changes are important for individuals, teams, leadership, and the company as a whole is a first step to being able to assess if effective learning is taking place. Our preliminary findings indicate that there is no single measure that can be used to assess how well people learn. However, once a company has defined what changes it expects to see, a combination of measures could be created to give insight into how effectively learning is happening.This paper aims to provide some examples of indicators of learning after an incident. Both in research and in practice a single metric is often used to assess whether learning is occurring. This study proposes a model that would allow companies to select appropriate metrics for various aspects of learning from incidents.}\",",
        "author": "Murphy, V. L. and Littlejohn, A..  and Rienties, B..  and King, S..  and Bryden, R.. ",
        "doi": "10.2118/190527-MS",
        "eprint": "https://onepetro.org/SPEHSE/proceedings-pdf/18HSE/3-18HSE/D031S032R002/1207195/spe-190527-ms.pdf",
        "keywords": "gaining contextual understanding, interviews, framework use or proposal",
        "month": "04",
        "pages": "D031S032R002",
        "series": "SPE International Conference and Exhibition on Health, Safety, Environment, and Sustainability",
        "title": "\"{How Do You Know If You\u2019re Learning from Incidents?}\",",
        "type": "proceedings",
        "url": "https://doi.org/10.2118/190527-MS",
        "volume": "Day 3 Wed, April 18, 2018",
        "year": "2018"
    },
    "6805998": {
        "abstract": "The number of security incidents is still increasing. The re-occurrence of past breaches shows that lessons have not been effectively learned across different organisations. This illustrates important weaknesses within information security management systems (ISMS). The sharing of recommendations between public and private organisations has, arguably, not been given enough attention across academic and industry. Many questions remain, for example, about appropriate levels of detail and abstraction that enable different organisations to learn from incidents that occur in other companies within the same or different industries. The Generic Security Template has been proposed, aiming to provide a unified way to share the lessons learned from real world security incidents. In particular, it adapts the graphical Goal Structuring Notation (GSN), to present lessons learned in a structured manner by mapping them to the security requirements of the ISMS. In this paper, we have shown how a Generic Security Template can be used to structure graphical overviews of specific incidents. We have also shown the template can be instantiated to communicate the findings from an investigation into the US VA data breach. Moreover, this paper has empirically evaluated this approach to the creation of a Generic Security Template; this provides users with an overview of the lessons derived from security incidents at a level of abstraction that can help to implement recommendations in future contexts that are different from those in which an attack originally took place.",
        "author": "He, Ying and Johnson, Chris and Renaud, Karen and Lu, Yu and Jebriel, Salem",
        "booktitle": "2014 6th International Conference on Computer Science and Information Technology (CSIT)",
        "doi": "10.1109/CSIT.2014.6805998",
        "issn": "",
        "keywords": "Context;Hazards;Medical services;Companies;Security;Standards;Sensitivity;Generic Security Template;lessons learned;security incident;Goal Structuring Notation, using existing models/approaches to structure lesson learning, data visualisation, framework use or proposal",
        "month": "March",
        "number": "",
        "pages": "178-188",
        "title": "An empirical study on the use of the Generic Security Template for structuring the lessons from information security incidents",
        "type": "INPROCEEDINGS",
        "volume": "",
        "year": "2014"
    },
    "AHMAD2015717": {
        "abstract": "Our case analysis presents and identifies significant and systemic shortcomings of the incident response practices of an Australian financial organization. Organizational Incident Response Teams accumulate considerable experience in addressing information security failures and attacks. Their first-hand experiences provide organizations with a unique opportunity to draw security lessons and insights towards improving enterprise-wide security management processes. However, previous research shows a distinct lack of communication and collaboration between the functions of incident response and security management, suggesting organizations are not learning from their incident experiences. We subsequently propose a number of lessons learned and a novel security-learning model.",
        "author": "Atif Ahmad and Sean B Maynard and Graeme Shanks",
        "doi": "https://doi.org/10.1016/j.ijinfomgt.2015.08.001",
        "issn": "0268-4012",
        "journal": "International Journal of Information Management",
        "keywords": "Information Security Management, Security learning, Incident Response Teams, Organizational learning, using existing models/approaches to structure lesson learning, interviews, case study or scenario, framework use or proposal",
        "number": "6",
        "pages": "717-723",
        "title": "A case analysis of information systems and security incident responses",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S026840121500078X",
        "volume": "35",
        "year": "2015"
    },
    "GRISPOS201762": {
        "abstract": "Security incidents detected by organizations are escalating in both scale and complexity. As a result, security incident response has become a critical mechanism for organizations in an effort to minimize the damage from security incidents. The final phase within many security incident response approaches is the feedback/follow-up phase. It is within this phase that an organization is expected to use information collected during an investigation in order to learn from an incident, improve its security incident response process and positively impact the wider security environment. However, recent research and security incident reports argue that organizations find it difficult to learn from incidents. A contributing factor to this learning deficiency is that industry focused security incident response approaches, typically, provide very little practical information about tools or techniques that can be used to extract lessons learned from an investigation. As a result, organizations focus on improving technical security controls and not examining or reassessing the effectiveness or efficiency of internal policies and procedures. An additional hindrance, to encouraging improvement assessments, is the absence of tools and/or techniques that organizations can implement to evaluate the impact of implemented enhancements in the wider organization. Hence, this research investigates the integration of lightweight agile retrospectives and meta-retrospectives, in a security incident response process, to enhance feedback and/or follow-up efforts. The research contribution of this paper is twofold. First, it presents an approach based on lightweight retrospectives as a means of enhancing security incident response follow-up efforts. Second, it presents an empirical evaluation of this lightweight approach in a Fortune 500 Financial organization's security incident response team.",
        "author": "George Grispos and William Bradley Glisson and Tim Storer",
        "doi": "https://doi.org/10.1016/j.diin.2017.07.006",
        "issn": "1742-2876",
        "journal": "Digital Investigation",
        "keywords": "Security incident response, Security investigations, Case study, Retrospectives, Incident learning, developing new/improved models/approaches to structure lesson learning, retrospectives, interviews",
        "pages": "62-73",
        "title": "Enhancing security incident response follow-up efforts with lightweight agile retrospectives",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S1742287616301293",
        "volume": "22",
        "year": "2017"
    },
    "LUKIC2012950": {
        "abstract": "Learning from Incidents (LFI) in the workplace has been gaining increasing importance in the Health, Safety and Environment context. Although organisations adopt a variety of LFI initiatives, it is often unclear what learning approaches are the most appropriate and the most effective for different types of incidents across a range of contexts. The aim of the paper is to surface factors that are important for effective Learning from Incidents (LFI). The paper builds on a conceptual framework for learning from incidents, developed through an earlier study. This conceptual framework was validated through empirical data collected at two multinational corporations in the energy sector. From this data a refined framework for learning from incidents was devised with five factors important for LFI: participants of learning, type of incidents, learning process, type of knowledge and learning context. This framework can be used as an evaluation tool and as a guidance tool to develop holistic, organisational learning approaches.",
        "author": "Dane Lukic and Allison Littlejohn and Anoush Margaryan",
        "doi": "https://doi.org/10.1016/j.ssci.2011.12.032",
        "issn": "0925-7535",
        "journal": "Safety Science",
        "keywords": "Learning from incidents, Safety, Organisational learning, Workplace learning, developing new/improved models/approaches to structure lesson learning, interviews, framework use or proposal",
        "note": "First International Symposium on Mine Safety Science and Engineering 2011",
        "number": "4",
        "pages": "950-957",
        "title": "A framework for learning from incidents in the workplace",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S0925753511003511",
        "volume": "50",
        "year": "2012"
    },
    "PATTERSON2023103309": {
        "abstract": "Cyber security incidents are now prevalent in many organisations. Arguably, those who can learn from security incidents and address the underlying causes will reduce the prevalence of similar ones in the future. This research provides a new examination of how organisations learn from incidents by systematically reviewing academic research on organisational learning from cyber security incidents and identifying further research needed in this area. To do this, it considers three research questions: what research has been conducted on learning from cyber security incidents, what learning practices in organisations have been found by research and what improvements have been recommended, and what further research is needed as organisations learn from such incidents. Using the PRISMA method, a total of 3,986 articles were extracted and, from these, a relevant set of 30 were selected for analysis to map the body of research, and to identify future research avenues. Despite learning lessons being recommended by both researchers and industry standards, our findings suggest that this advice is not being fully adopted by organisations. Importantly, these studies have found inadequate participation in learning activities, with superficial causal investigations, scarce effort on ensuring lessons are implemented and no evaluation of whether the actions taken actually reduce future security incidents. More research is needed to understand the right level and which learning practices to invest in for the greatest impact. For practitioners, this review discusses the essential elements of an effective process to learn from incidents. This review provides academics with a novel synthesis of the research undertaken on this topic, enabling them to incorporate the significant findings into their work and potentially explore the research agenda suggested.",
        "author": "Clare M. Patterson and Jason R.C. Nurse and Virginia N.L. Franqueira",
        "doi": "https://doi.org/10.1016/j.cose.2023.103309",
        "issn": "0167-4048",
        "journal": "Computers & Security",
        "keywords": "Cyber security, Incident investigation, Incident response, Lessons learned, Learning process, Organisational learning, Post-incident review, Security incident, Systematic literature review, Research agenda, gaining contextual understanding, surveys",
        "pages": "103309",
        "title": "Learning from cyber security incidents: A systematic review and future research agenda",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S0167404823002195",
        "volume": "132",
        "year": "2023"
    },
    "PATTERSON2024103699": {
        "abstract": "Learning from cyber incidents is crucial for organisations to enhance their cyber resilience and effectively respond to evolving threats. This study employs neo-institutional and organisational learning theories to examine how organisations learn from incidents and gain insights into the challenges they face. Drawing on qualitative research methods, interviews were conducted with 34 security practitioners from organisations operating in the UK spanning a range of industries. The findings highlight the importance of consciously evaluating learning practices and creating a culture of openness to hear about incidents from employees, customers and suppliers. Deciding which incidents to learn from, as well as who should participate in the learning process, emerged as critical considerations. Overcoming defensiveness and addressing systemic causes were recognised as barriers to effective learning. The study emphasises the need to assess the value and impact of identified lessons and to avoid superficial reviews that treat symptoms rather than underlying causes to improve resilience. While progress has been made in learning from incidents, further enhancements are needed. Practical recommendations have been proposed to suggest how organisations may gain valuable insights for maximising the benefits derived from incident learning. This research contributes to the existing knowledge on organisational learning and informs future studies exploring the social and political influences on the learning process. By considering the suggested recommendations, organisations may strengthen their cyber security, foster a culture of continuous improvement, and respond effectively to the dynamic cyber security landscape.",
        "author": "Clare M. Patterson and Jason R.C. Nurse and Virginia N.L. Franqueira",
        "doi": "https://doi.org/10.1016/j.cose.2023.103699",
        "issn": "0167-4048",
        "journal": "Computers & Security",
        "keywords": "Cyber security incidents, Organisational learning, Post-incident review, Cyber resilience, Learning practices, Lessons learned, Neo-institutional theory, Isomorphic pressures, gaining contextual understanding, interviews",
        "pages": "103699",
        "title": "\u201cI don't think we're there yet\u201d: The practices and challenges of organisational learning from cyber security incidents",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S0167404823006090",
        "volume": "139",
        "year": "2024"
    },
    "doi:10.1080/17538157.2016.1255629": {
        "abstract": " Security incidents can have negative impacts on healthcare organizations, and the security of medical records has become a primary concern of the public. However, previous studies showed that organizations had not effectively learned lessons from security incidents. Incident learning as an essential activity in the \u201cfollow-up\u201d phase of security incident response lifecycle has long been addressed but not given enough attention. This paper conducted a case study in a healthcare organization in China to explore their current obstacles in the practice of incident learning. We interviewed both IT professionals and healthcare professionals. The results showed that the organization did not have a structured way to gather and redistribute incident knowledge. Incident response was ineffective in cycling incident knowledge back to inform security management. Incident reporting to multiple stakeholders faced a great challenge. In response to this case study, we suggest the security assurance modeling framework to address those obstacles.",
        "author": "Ying He and Chris Johnson",
        "doi": "10.1080/17538157.2016.1255629",
        "eprint": " https://doi.org/10.1080/17538157.2016.1255629 ,",
        "journal": "Informatics for Health and Social Care",
        "keywords": "using existing models/approaches to structure lesson learning, interviews, framework use or proposal, case study or scenario",
        "note": "PMID: 28068150",
        "number": "4",
        "pages": "393--408",
        "publisher": "Taylor \\& Francis",
        "title": "Challenges of information security incident learning: An industrial case study in a Chinese healthcare organization, framework use or proposal",
        "type": "article",
        "url": " https://doi.org/10.1080/17538157.2016.1255629 ,",
        "volume": "42",
        "year": "2017"
    },
    "https://doi.org/10.1002/asi.24311": {
        "abstract": "Abstract Digital assets of organizations are under constant threat from a wide assortment of nefarious actors. When threats materialize, the consequences can be significant. Most large organizations invest in a dedicated information security management (ISM) function to ensure that digital assets are protected. The ISM function conducts risk assessments, develops strategy, provides policies and training to define roles and guide behavior, and implements technological controls such as firewalls, antivirus, and encryption to restrict unauthorized access. Despite these protective measures, incidents (security breaches) will occur. Alongside the security management function, many organizations also retain an incident response (IR) function to mitigate damage from an attack and promptly restore digital services. However, few organizations integrate and learn from experiences of these functions in an optimal manner that enables them to not only respond to security incidents, but also proactively maneuver the threat environment. In this article we draw on organizational learning theory to develop a conceptual framework that explains how the ISM and IR functions can be better integrated. The strong integration of ISM and IR functions, in turn, creates learning opportunities that lead to organizational security benefits including: increased awareness of security risks, compilation of threat intelligence, removal of flaws in security defenses, evaluation of security defensive logic, and enhanced security response.",
        "author": "Ahmad, Atif and Desouza, Kevin C. and Maynard, Sean B. and Naseer, Humza and Baskerville, Richard L.",
        "doi": "https://doi.org/10.1002/asi.24311",
        "eprint": "https://asistdl.onlinelibrary.wiley.com/doi/pdf/10.1002/asi.24311",
        "journal": "Journal of the Association for Information Science and Technology",
        "keywords": "integrating ir and ism teams, case study or scenario",
        "number": "8",
        "pages": "939-953",
        "title": "How integration of cyber security management and incident response enables organizational learning",
        "type": "article",
        "url": "https://asistdl.onlinelibrary.wiley.com/doi/abs/10.1002/asi.24311",
        "volume": "71",
        "year": "2020"
    },
    "info15020106": {
        "abstract": "Purpose: The purpose of this research paper was to analyse the counterstrategies to mitigate cybersecurity challenges using organisational learning loops amidst major crises in the Higher Education and Research Sector (HERS). The authors proposed the learning loop framework revealing several counterstrategies to mitigate cybersecurity issues in HERS. The counterstrategies are explored, and their implications for research and practice are discussed. Methodology: The qualitative methodology was adopted, and semi-structured interviews with cybersecurity experts and top managers were conducted. Results: This exploratory paper proposed the learning loop framework revealing introducing new policies and procedures, changing existing systems, partnership with other companies, integrating new software, improving employee learning, enhancing security, and monitoring and evaluating security measures as significant counterstrategies to ensure the cyber-safe working environment in HERS. These counterstrategies will help to tackle cybersecurity in HERS, not only during the current major crisis but also in the future. Implications: The outcomes provide insightful implications for both theory and practice. This study proposes a learning framework that prioritises counterstrategies to mitigate cybersecurity challenges in HERS amidst a major crisis. The proposed model can help HERS be more efficient in mitigating cybersecurity issues in future crises. The counterstrategies can also be tested, adopted, and implemented by practitioners working in other sectors to mitigate cybersecurity issues during and after major crises. Future research can focus on addressing the shortcomings and limitations of the proposed learning framework adopted by HERS.",
        "article-number": "106",
        "author": "Mahmood, Samreen and Chadhar, Mehmood and Firmin, Selena",
        "doi": "10.3390/info15020106",
        "issn": "2078-2489",
        "journal": "Information",
        "keywords": "developing new/improved models/approaches to structure lesson learning, interviews, framework use or proposal",
        "number": "2",
        "title": "Countermeasure Strategies to Address Cybersecurity Challenges Amidst Major Crises in the Higher Education and Research Sector: An Organisational Learning Perspective",
        "type": "Article",
        "url": "https://www.mdpi.com/2078-2489/15/2/106",
        "volume": "15",
        "year": "2024"
    }
};